import { Agent, AgentStatus } from './types';

export const DEFAULT_AGENTS: Omit<Agent, 'id' | 'status' | 'output' | 'error' | 'outputJson'>[] = [
  {
    name: 'Summarizer',
    prompt: 'Summarize the following document content in three key bullet points. Be concise and accurate.',
  },
  {
    name: 'Entity Extractor',
    prompt: 'Extract all named entities (people, organizations, locations, dates) from the document. Respond with ONLY a valid JSON array of objects, where each object has "name" and "type" keys. Example: [{"name": "Jane Doe", "type": "Person"}]',
  },
  {
    name: 'Sentiment Analyzer',
    prompt: 'Analyze the overall sentiment of the document. Is it positive, negative, or neutral? Provide a confidence score. Respond with ONLY a valid JSON object with "sentiment" and "confidence" keys. Example: {"sentiment": "Positive", "confidence": 0.95}',
  },
  {
    name: 'Compliance Check',
    prompt: 'Assume you are a compliance officer. Review the text for any potential compliance issues related to FDA regulations. List any findings or state that none were found.',
  },
];

export const FLOWER_THEMES = [
    { name: 'Rose Quartz', colors: { primary: '#e91e63', bg: '#fce4ec', text: '#3c2a2f' } },
    { name: 'Lavender Mist', colors: { primary: '#9c27b0', bg: '#f3e5f5', text: '#3c2740' } },
    { name: 'Sunflower Glow', colors: { primary: '#fbc02d', bg: '#fff8e1', text: '#4d3d00' } },
    { name: 'Ocean Petal', colors: { primary: '#03a9f4', bg: '#e1f5fe', text: '#013a5a' } },
    { name: 'Mint Blossom', colors: { primary: '#4caf50', bg: '#e8f5e9', text: '#1e4620' } },
    { name: 'Coral Charm', colors: { primary: '#ff7043', bg: '#fbe9e7', text: '#5d2b1a' } },
    { name: 'Iris Indigo', colors: { primary: '#3f51b5', bg: '#e8eaf6', text: '#1a237e' } },
    { name: 'Poppy Red', colors: { primary: '#f44336', bg: '#ffebee', text: '#5b1813' } },
    { name: 'Orchid Oasis', colors: { primary: '#673ab7', bg: '#ede7f6', text: '#311b92' } },
    { name: 'Marigold Burst', colors: { primary: '#ff9800', bg: '#fff3e0', text: '#663d00' } },
    { name: 'Sakura Dream', colors: { primary: '#ec407a', bg: '#fce4ec', text: '#5b182f' } },
    { name: 'Teal Tulip', colors: { primary: '#009688', bg: '#e0f2f1', text: '#003d38' } },
    { name: 'Dahlia Plum', colors: { primary: '#8e24aa', bg: '#f3e5f5', text: '#3c0d4a' } },
    { name: 'Buttercup Yellow', colors: { primary: '#ffeb3b', bg: '#fffde7', text: '#5d550c' } },
    { name: 'Hydrangea Blue', colors: { primary: '#2196f3', bg: '#e3f2fd', text: '#0c3d64' } },
    { name: 'Peony Pink', colors: { primary: '#f06292', bg: '#fce4ec', text: '#5b263a' } },
    { name: 'Sage Green', colors: { primary: '#8bc34a', bg: '#f1f8e9', text: '#334a1e' } },
    { name: 'Garnet Gem', colors: { primary: '#c2185b', bg: '#f8bbd0', text: '#5c0c2b' } },
    { name: 'Amber Blaze', colors: { primary: '#ffc107', bg: '#fff8e1', text: '#664c02' } },
    { name: 'Wisteria Wonder', colors: { primary: '#7e57c2', bg: '#ede7f6', text: '#34235e' } },
];

export const LOCALIZATION = {
    en: {
        title: 'Agentic AI Document Intelligence',
        uploadHint: 'PDF or TXT',
        uploadDocument: 'Upload a document',
        documentControl: 'Document Control',
        addAgent: 'Add Agent',
        agentWorkflow: 'Agent Workflow',
        runWorkflow: 'Run Workflow',
        running: 'Running...',
        addAgentToStart: 'Add an agent to start building your workflow.',
        resultsDashboard: 'Results Dashboard',
        extractedEntities: 'Extracted Entities',
        sentimentAnalysis: 'Sentiment Analysis',
        workflow: 'Workflow',
        dashboard: 'Dashboard',
        notes: 'Notes',
        yourNotes: 'Your Notes',
        notesPreview: 'Notes Preview',
        textToColor: 'Text to Color',
        selectColor: 'Select Color',
        applyColor: 'Apply Color',
        settings: 'Settings',
        theme: 'Theme',
        language: 'Language',
        style: 'Style',
        mode: 'Mode',
        light: 'Light',
        dark: 'Dark',
        textToColorPlaceholder: 'Enter text to color...',
    },
    'zh-TW': {
        title: '代理式 AI 文件智能平台',
        uploadHint: 'PDF 或 TXT',
        uploadDocument: '上傳文件',
        documentControl: '文件控制',
        addAgent: '新增代理',
        agentWorkflow: '代理工作流程',
        runWorkflow: '執行工作流程',
        running: '運行中...',
        addAgentToStart: '新增代理以開始建立您的工作流程。',
        resultsDashboard: '結果儀表板',
        extractedEntities: '提取的實體',
        sentimentAnalysis: '情感分析',
        workflow: '工作流程',
        dashboard: '儀表板',
        notes: '筆記',
        yourNotes: '您的筆記',
        notesPreview: '筆記預覽',
        textToColor: '文字上色',
        selectColor: '選擇顏色',
        applyColor: '套用顏色',
        settings: '設定',
        theme: '主題',
        language: '語言',
        style: '風格',
        mode: '模式',
        light: '淺色',
        dark: '深色',
        textToColorPlaceholder: '輸入要上色的文字...',
    },
};
